name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Update README with HTML report link
        if: always()
        run: |
          echo "## Playwright Test Report" >> $GITHUB_STEP_SUMMARY
          echo "Download the HTML report artifact and open the index.html file to view the test results." >> $GITHUB_STEP_SUMMARY
          echo "Artifact URL: \`https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\`" >> $GITHUB_STEP_SUMMARY
