name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Get pull request description
        if: github.event_name == 'pull_request'
        id: pr_description
        run: echo "::set-output name=description::${{ github.event.pull_request.body }}"

      - name: Run Playwright tests
        run: |
          if [[ "${{ github.event_name == 'pull_request' && contains(steps.pr_description.outputs.description, '[x] Update Snapshots') && github.event.pull_request.user.login == github.repository_owner }}" == "true" ]]; then
            yarn playwright test --update-snapshots
          else
            yarn playwright test
          fi

      - name: Commit and push updated snapshots
        if: github.event_name == 'pull_request' && contains(steps.pr_description.outputs.description, '[x] Update Snapshots') && github.event.pull_request.user.login == github.repository_owner
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Playwright snapshots" || echo "No changes to commit"
          git push

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
